#!/bin/bash

### BEGIN INIT INFO
# Provides:          munin
# Required-Start:    $local_fs $network $named $remote_fs $syslog
# Required-Stop:     $local_fs $network $named $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: munin daemon
# Description:       Munin is a free and open-source computer system monitoring, network monitoring and infrastructure monitoring software application.
### END INIT INFO

PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
export PATH

if [ $(id -u) -ne 0 ]; then
    echo -e "\033[1;31m[E]\033[0m  You must have root permissions for run this script, please use sudo and try again." >&2
    exit 4
fi

name=munin

###############################################################
########## Maybe you need to modify these variables. ##########

### In the most cases, the binary file of program is in `/usr/bin` or `/usr/local/bin`.
### Try using `which munin-node` `which munin-cgi-graph` `which munin-cgi-html` and `which spawn-fcgi` to find the full path, or just use `munin-node` `munin-cgi-graph` `munin-cgi-html` and `spawn-fcgi` if it is in `$PATH`.
bin=/usr/local/munin/sbin/munin-node
cgiGraphBin=/usr/local/munin/lib/cgi/munin-cgi-graph
cgiHtmlBin=/usr/local/munin/lib/cgi/munin-cgi-html
spawnFcgi=/usr/bin/spawn-fcgi
if [ ! -x "$bin" ] || [ ! -x "$cgiGraphBin" ] || [ ! -x "$cgiHtmlBin" ] || [ ! -x "$spawnFcgi" ]; then
    echo -e "\033[1;31m[E]\033[0m  Can not find $bin $cgiGraphBin $cgiHtmlBin or $spawnFcgi, maybe the program isn't installed." >&2
    exit 5
fi

### In the most cases, the configuration file of program is in `/etc`. You can create your own configuration file and edit this variable to the new path.
config=/data/etc/munin/munin-node.conf
if [ ! -r "$config" ]; then
    echo -e "\033[1;31m[E]\033[0m  The configuration file isn't found, maybe the path ($config) is wrong." >&2
    exit 6
fi

### By default, the pid file of program is in `/var/run`. So you don't need to edit this variable.
pidFile=/var/run/munin/munin-node.pid
cgiGraphPidFile=/var/run/munin/munin-cgi-graph.pid
cgiHtmlPidFile=/var/run/munin/munin-cgi-html.pid

cgiGraphSocketFile=/tmp/munin/munin-cgi-graph.sock
cgiHtmlSocketFile=/tmp/munin/munin-cgi-html.sock

cgiForkChildrenNum=3

##########                                           ##########
###############################################################

script=$(basename "$0")

getPid() {
    ### Delete spaces, tabs and newlines.
    pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')

    ### `$pidFile` may be blank. If the process exists, `! kill -0 $pid 2>/dev/null` will return 1.
    if [ -z $pid ] || ! kill -0 $pid 2>/dev/null; then
        rm -f $pidFile
        unset pid
    fi

    i=0
    awk 1 $cgiGraphPidFile 2>/dev/null | while read line; do
        if [ -z $line ] || ! kill -0 $line 2>/dev/null; then
            continue
        fi

        cgiGraphPids[$i]=$line

        (( i++ ))
    done

    if [ ${#cg12iGraphPid[*]} -eq 0 ]; then
        rm -f $cgiGraphPidFile
    fi

    i=0
    awk 1 $cgiHtmlPidFile | while read line; do
        if [ -z $line ] || ! kill -0 $line 2>/dev/null; then
            continue
        fi

        cgiHtmlPids[$i]=$line

        (( i++ ))
    done

    if [ ${#cgiHtmlPids[*]} -eq 0 ]; then
        rm -f $cgiHtmlPidFile
    fi
}

doStart() {
    echo -en "\033[1;36m[I]\033[0m  Starting $name"

    if ! $bin --config "$config" || \
        ### WARNING: You can't specify a config file for munin-cgi. You must install munin from source if you want to use a custom config file.
        ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiGraphSocketFile -u munin -g munin -U munin -G munin -P $cgiGraphPidFile $cgiGraphBin || \
        ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiHtmlSocketFile -u munin -g munin -U munin -G munin -P $cgiHtmlPidFile $cgiHtmlBin; then
        echo -e "\n\033[1;31m[E]\033[0m  Start $name error."
        exit 1
    fi

    echo -n '.'
    getPid

    ### Successfully start the program if the process exists after 5 seconds.
    for (( i=0; i<=5; i++ )); do
        if ! kill -0 $pid 2>/dev/null; then
            echo -e "\n\033[1;31m[E]\033[0m  Start munin-node failed."
            exit 1
        fi

        for cgiGraphPid in ${cgiGraphPids[*]}; do
            if ! kill -0 $cgiGraphPid 2>/dev/null; then
                echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-graph failed."
                exit 1
            fi
        done

        for cgiHtmlPid in ${cgiHtmlPids[*]}; do
            if ! kill -0 $cgiHtmlPid 2>/dev/null; then
                echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-html failed."
                exit 1
            fi
        done

        echo -n '.'
        sleep 1
    done

    echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
}

doStop() {
    echo -en "\033[1;36m[I]\033[0m  Stopping $name"
    if ! kill $pid 2>/dev/null; then
        echo -e "\n\033[1;31m[E]\033[0m  Stop munin-node error."
        exit 1
    fi

    for cgiGraphPid in ${cgiGraphPids[*]}; do
        if ! kill $cgiGraphPid; then
            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-graph error."
            exit 1
        fi
    done

    for cgiHtmlPid in ${cgiHtmlPids[*]}; do
        if ! kill $cgiHtmlPid; then
            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-html error."
            exit 1
        fi
    done

    ### Successfully stop the program if the process doesn't exists in 10 seconds.
    for (( i=0; i<=11; i++ )); do
        if kill -0 $pid 2>/dev/null; then
            if [ $i -ge 10 ]; then
                echo -e "\n\033[1;31m[E]\033[0m  Stop munin-node failed."
                exit 1
            fi

            continue
        fi

        for cgiGraphPid in ${cgiGraphPids[*]}; do
            if kill -0 $cgiGraphPid 2>/dev/null; then
                if [ $i -ge 10 ]; then
                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi-graph failed."
                    exit 1
                fi

                continue
            fi
        done

        for cgiHtmlPid in ${cgiHtmlPids[*]}; do
            if kill -0 $cgiHtmlPid 2>/dev/null; then
                if [ $i -ge 10 ]; then
                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-html-graph failed."
                    exit 1
                fi

                continue
            fi
        done

        echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
        break
    done
}

case "$1" in
    start)
    getPid
    if [ $pid ] || [ ${#cgiHtmlPids[*]} -gt 0 ] || [ ${#cgiGraphPids[*]} -gt 0 ]; then
        echo -e "\033[1;33m[W]\033[0m  $name is already running:"

        if [ $pid ]; then
            echo -e "\033[1;33m[W]\033[0m  munin-node pid = $pid"
        fi

        if [ ${#cgiGraphPids[*]} -gt 0 ]; then
            echo -e "\033[1;33m[W]\033[0m  munin-cgi-graph pids are ${cgiGraphPids[*]}"
        fi

        if [ ${#cgiHtmlPids[*]} -gt 0 ]; then
            echo -e "\033[1;33m[W]\033[0m  munin-cgi-html pids are ${cgiHtmlPids[*]}"
        fi
    fi

    doStart
    ;;

    stop)
    getPid
    if [ -z $pid ] && [ ${#cgiHtmlPids[*]} -eq 0 ] && [ ${#cgiGraphPids[*]} -eq 0 ]; then
        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
        exit 0
    fi

    doStop
    ;;

    kill)
    getPid
    if [ -z $pid ] && [ ${#cgiHtmlPids[*]} -eq 0 ] && [ ${#cgiGraphPids[*]} -eq 0 ]; then
        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
        exit 0
    fi

    echo -e "\033[1;36m[I]\033[0m  Forcefully killing the process of $name..."

    if ! kill -9 $pid 2>/dev/null; then
        echo -e "\n\033[1;31m[E]\033[0m  Start munin-node failed."
        exit 1
    fi
    rm -f $pidFile

    for cgiGraphPid in ${cgiGraphPids[*]}; do
        if ! kill -9 $cgiGraphPid 2>/dev/null; then
            echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-graph failed."
            exit 1
        fi
    done
    rm -f $cgiGraphPidFile

    for cgiHtmlPid in ${cgiHtmlPids[*]}; do
        if ! kill -9 $cgiHtmlPid 2>/dev/null; then
            echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi-html failed."
            exit 1
        fi
    done
    rm -f $cgiHtmlPidFile

    echo -e "\033[1;32m[N]\033[0m  Kill $name done."
    ;;

    restart)
    getPid
    if [ -z $pid ]; then
        echo -e "\033[1;33m[W]\033[0m  $name isn't running"

        doStart
        exit 0
    fi

    echo -e "\033[1;36m[I]\033[0m  Restarting $name:"

    doStop
    doStart
    ;;

    force-reload)
    getPid
    if [ -z $pid ]; then
        echo -e "\033[1;31m[E]\033[0m  $name isn't running"
        exit 7
    fi

    echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
    doStop
    doStart
    ;;

    status)
    getPid
    if [ -z $pid ] && [ ${#cgiHtmlPids[*]} -eq 0 ] && [ ${#cgiGraphPids[*]} -eq 0 ]; then
        echo -e "\033[1;32m[N]\033[0m  $name isn't running."
        exit 3
    fi

    echo -e "\033[1;33m[W]\033[0m  $name is already running:"

    if [ $pid ]; then
        echo -e "\033[1;33m[W]\033[0m  munin-node pid = $pid"
    fi

    if [ ${#cgiGraphPids[*]} -gt 0 ]; then
        echo -e "\033[1;33m[W]\033[0m  munin-cgi-graph pids are ${cgiGraphPids[*]}"
    fi

    if [ ${#cgiHtmlPids[*]} -gt 0 ]; then
        echo -e "\033[1;33m[W]\033[0m  munin-cgi-html pids are ${cgiHtmlPids[*]}"
    fi
    ;;

    *)
    ### You can't reload the configuration file in here.
#   echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|reload|status}" >&2
    echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|status}." >&2
    exit 3
    ;;
esac

exit 0
