#!/bin/bash

### BEGIN INIT INFO
# Provides:          munin
# Required-Start:    $local_fs $network $named $remote_fs $syslog
# Required-Stop:     $local_fs $network $named $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: munin daemon
# Description:       Munin is a free and open-source computer system monitoring, network monitoring and infrastructure monitoring software application.
### END INIT INFO

PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
export PATH

if [ $(id -u) -ne 0 ]; then
    echo -e "\033[1;31m[E]\033[0m  You must have root permissions for run this script, please use sudo and try again." >&2
    exit 4
fi

name=munin

###############################################################
########## Maybe you need to modify these variables. ##########

### In the most cases, the binary file of program is in `/usr/bin` or `/usr/local/bin`.
### Try using `which munin-node` `which spawn-fcgi` and `which fcgiwrap` to find the full path, or just use `munin-node` `spawn-fcgi` and `fcgiwrap` if it is in `$PATH`.
prefix=/usr/local/munin
node=$prefix/sbin/munin-node
spawnFcgi=/usr/bin/spawn-fcgi
fcgiwrap=/usr/sbin/fcgiwrap
if [ ! -x "$node" ] || [ ! -x "$spawnFcgi" ] || [ ! -x "$fcgiwrap" ]; then
    echo -e "\033[1;31m[E]\033[0m  Can not find $node $spawnFcgi or $fcgiwrap, maybe the program isn't installed." >&2
    exit 5
fi

### In the most cases, the configuration file of program is in `/etc`. You can create your own configuration file and edit this variable to the new path.
config=/data/etc/munin/munin-node.conf
if [ ! -r "$config" ]; then
    echo -e "\033[1;31m[E]\033[0m  The configuration file isn't found, maybe the path ($config) is wrong." >&2
    exit 6
fi

### By default, the pid file of program is in `/var/run`. So you don't need to edit this variable.
pidDir=/var/run/munin
nodePidFile=$pidDir/munin-node.pid
cgiPidFile=$pidDir/munin-cgi.pid

cgiSocketFile=/tmp/munin-cgi.sock
cgiForkChildrenNum=3

##########                                           ##########
###############################################################

script=$(basename "$0")

getPid() {
    ### Delete spaces, tabs and newlines.
    nodePid=$(cat $nodePidFile 2>/dev/null | tr -d ' \t\n')

    ### `$nodePidFile` may be blank. If the process exists, `! kill -0 $nodePid 2>/dev/null` will return 1.
    if [ -z $nodePid ] || ! kill -0 $nodePid 2>/dev/null; then
        rm -f $nodePidFile
        unset nodePid
    fi

    unset cgiPids

    i=0
    while read line; do
        line=$(echo -n "$line" | tr -d ' \t\n')

        if [ -z $line ] || ! kill -0 $line 2>/dev/null; then
            continue
        fi

        cgiPids[$i]=$line

        (( i++ ))
    done < <(awk 1 $cgiPidFile 2>/dev/null)

    if [ ${#cgiPids[*]} -eq 0 ]; then
        rm -f $cgiPidFile
    fi
}

doStart() {
    echo -en "\033[1;36m[I]\033[0m  Starting $name."

    if [ ! -d "$pidDir" ]; then
        mkdir -p $pidDir
        chown -R munin:munin $pidDir
    fi

    if ! $node --config "$config"; then
        echo -e "\n\033[1;31m[E]\033[0m  Start munin-node error."
        exit 1
    fi

    ### WARNING: You can't specify a config file for munin-cgi. You must install munin from source if you want to use a custom config file.
    if ! $spawnFcgi -F $cgiForkChildrenNum -s $cgiSocketFile -u munin -g munin -U munin -G munin -P $cgiPidFile -- $fcgiwrap -f; then
        echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi error."
        exit 1
    fi
    chmod 666 $cgiSocketFile

    getPid

    ### Successfully start the program if the process exists after 5 seconds.
    for (( i=0; i<=5; i++ )); do
        if ! kill -0 $nodePid 2>/dev/null; then
            echo -e "\n\033[1;31m[E]\033[0m  Start munin-node failed."
            exit 1
        fi

        if [ ${#cgiPids[*]} -eq 0 ]; then
            echo -e "\n\033[1;33m[W]\033[0m  Start munin-cgi failed."
        fi

        for cgiPid in ${cgiPids[*]}; do
            if ! kill -0 $cgiPid 2>/dev/null; then
                echo -e "\n\033[1;31m[E]\033[0m  Start munin-cgi failed."
                exit 1
            fi
        done

        sleep 1
        echo -n '.'
    done

    echo -e "\n\033[1;32m[N]\033[0m  Start $name success."
}

doStop() {
    echo -en "\033[1;36m[I]\033[0m  Stopping $name."

    if ! kill $nodePid 2>/dev/null; then
        echo -e "\n\033[1;31m[E]\033[0m  Stop munin-node error. Try using $script kill."
        exit 1
    fi

    for cgiPid in ${cgiPids[*]}; do
        if ! kill $cgiPid; then
            echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi error. Try using $script kill."
            exit 1
        fi
    done

    ### Successfully stop the program if the process doesn't exists in 10 seconds.
    for (( i=0; i<=11; i++ )); do
        sleep 1
        echo -n '.'

        if kill -0 $nodePid 2>/dev/null; then
            if [ $i -ge 10 ]; then
                echo -e "\n\033[1;31m[E]\033[0m  Stop munin-node failed. Try using $script kill."
                exit 1
            fi

            continue
        fi

        for cgiPid in ${cgiPids[*]}; do
            if kill -0 $cgiPid 2>/dev/null; then
                if [ $i -ge 10 ]; then
                    echo -e "\n\033[1;31m[E]\033[0m  Stop munin-cgi failed. Try using $script kill."
                    exit 1
                fi

                continue
            fi
        done

        echo -e "\n\033[1;32m[N]\033[0m  Stop $name success."
        break
    done
}

case "$1" in
    start)
    getPid
    if [ $nodePid ] || [ ${#cgiPids[*]} -gt 0 ]; then
        echo -e "\033[1;33m[W]\033[0m  $name is already running:"

        if [ $nodePid ]; then
            echo -e "\033[1;33m[W]\033[0m  munin-node pid = $nodePid."
        fi

        if [ ${#cgiPids[*]} -gt 0 ]; then
            echo -e "\033[1;33m[W]\033[0m  munin-cgi pids are ${cgiPids[*]}."
        fi

        exit 0
    fi

    doStart
    ;;

    stop)
    getPid
    if [ -z $nodePid ] && [ ${#cgiPids[*]} -eq 0 ]; then
        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
        exit 0
    fi

    doStop
    ;;

    kill)
    getPid
    if [ -z $nodePid ] && [ ${#cgiPids[*]} -eq 0 ]; then
        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
        exit 0
    fi

    echo -e "\033[1;36m[I]\033[0m  Forcefully killing the process of $name..."

    if ! kill -9 $nodePid 2>/dev/null; then
        echo -e "\033[1;31m[E]\033[0m  Kill munin-node failed."
        exit 1
    fi
    rm -f $nodePidFile

    for cgiPid in ${cgiPids[*]}; do
        if ! kill -9 $cgiPid 2>/dev/null; then
            echo -e "\033[1;31m[E]\033[0m  Kill munin-cgi failed."
            exit 1
        fi
    done
    rm -f $cgiPidFile

    echo -e "\033[1;32m[N]\033[0m  Kill $name done."
    ;;

    restart)
    getPid
    if [ -z $nodePid ]; then
        echo -e "\033[1;33m[W]\033[0m  $name isn't running."
        doStart
        exit 0
    fi

    echo -e "\033[1;36m[I]\033[0m  Restarting $name:"
    doStop
    doStart
    ;;

    force-reload)
    getPid
    if [ -z $nodePid ]; then
        echo -e "\033[1;31m[E]\033[0m  $name isn't running."
        exit 7
    fi

    echo -e "\033[1;36m[I]\033[0m  Forcefully reloading (restarting) $name:"
    doStop
    doStart
    ;;

    status)
    getPid
    if [ -z $nodePid ] && [ ${#cgiPids[*]} -eq 0 ]; then
        echo -e "\033[1;32m[N]\033[0m  $name isn't running."
        exit 3
    fi

    echo -e "\033[1;32m[N]\033[0m  $name is already running:"

    if [ $nodePid ]; then
        echo -e "\033[1;32m[N]\033[0m  munin-node pid = $nodePid."
    fi

    if [ ${#cgiPids[*]} -gt 0 ]; then
        echo -e "\033[1;32m[N]\033[0m  munin-cgi pids are ${cgiPids[*]}."
    fi

    ;;

    *)
    echo "Usage: [sudo] $script {start|stop|kill|restart|force-reload|status}." >&2
    exit 3
    ;;
esac

exit 0
