#! /bin/bash

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: nginx daemon
# Description:       starts and stop the nginx web server
### END INIT INFO

bin=/usr/local/nginx/sbin/nginx
config=/home/www/etc/nginx/nginx.conf
pidFile=/var/run/nginx.pid
if [ -f "$pidFile" ]; then
    pid=$(cat $pidFile)
    checkProgress=$(kill -0 $pid 2>&1 > /dev/null && echo -n $?)
    if [ "$checkProgress" != "0" ]; then
        rm -f $pidFile
        unset pid
    fi
fi
script=/etc/init.d/nginx

nginx() {
    $bin -c "$config"
}

doStart() {
    if [ "$pid" ]; then
        echo "nginx already running. pid = $pid"
    else
        nginx
        echo 'Done.'
    fi
}

doStop() {
    if [ "$pid" ]; then
        kill $pid
        echo 'Done.'
    else
        echo 'nginx not running.'
    fi
}

doRestart() {
    if [ "$pid" ]; then
        echo 'Stopping nginx...'
        kill $pid
        echo -e 'Done.\nStarting nginx...'
        nginx
        echo 'Done.'
    else
        echo -e 'nginx not running.\nStarting nginx...'
        nginx
        echo 'Done.'
    fi
}

doReload() {
    if [ "$pid" ]; then
        kill -HUP $pid
        echo 'Done.'
    else
        echo -e 'nginx not running.\nStarting nginx...'
        nginx
        echo 'Done.'
    fi
}

checkStatus() {
    if [ "$pid" ]; then
        echo "nginx is running. pid = $pid"
    else
        echo 'nginx not running.'
    fi
}

case "$1" in
    start)
    echo 'Starting nginx...'
    doStart
    ;;
    stop)
    echo 'Stopping nginx...'
    doStop
    ;;
    reload)
    echo 'Reloading nginx configuration...'
    doReload
    ;;
    restart)
    echo 'Restarting nginx: '
    doRestart
    ;;
    status)
    checkStatus
    ;;
    *)
    echo "Usage: $script {start|stop|restart|reload|status}" >&2
    exit 3
    ;;
esac

exit 0
