#! /bin/sh

### BEGIN INIT INFO
# Provides:          php-fpm
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php-fpm
# Description:       starts the PHP FastCGI Process Manager daemon
### END INIT INFO

name=php-fpm
bin=/usr/local/php/sbin/$name
config=/home/www/etc/php/$name.conf
ini=/home/www/etc/php/php.ini
pidFile=/var/run/$name.pid

getPid() {
    ### Delete spaces, tabs and newlines.
    pid=$(cat $pidFile 2>/dev/null | tr -d ' \t\n')
    if [ "$pid" ] && [ ! -d "/proc/$pid" ]; then
        rm -f $pidFile
        unset pid
    fi
}

### Successfully start the application if the progress exists after 3 seconds.
doStart() {
    echo -en "\033[1;36m[I]\033[0m  Starting $name"
    ### Block zend version notice.
    $bin -c "$ini" -y "$config" > /dev/null 2>&1

    getPid
    for (( i=0; i<=5; i++ )); do
        if [ -d "/proc/$pid" ]; then
            echo -n '.'
            sleep 1
        else
            echo -e "\n\033[1;31m[E]\033[0m  Start $name failed."
            exit 1
        fi
    done
    echo -e "\n\033[1;32m[N]\033[0m  Start $name succeeded."
}

### Successfully stop the application if the progress doesn't exists in 10 seconds.
doStop() {
    echo -en "\033[1;36m[I]\033[0m  Gracefully stopping $name"
    kill -QUIT $pid

    for (( i=0; i<=10; i++ )); do
        if [ -d "/proc/$pid" ]; then
            if [ "$i" = "10" ]; then
                echo -e "\n\033[1;31m[E]\033[0m  Stop $name failed. Try using $0 kill."
                exit 1
            fi
            echo -n '.'
            sleep 1
        else
            ### Just for restart.
            unset pid
            echo -e "\n\033[1;32m[N]\033[0m  Stop $name succeeded."
            break
        fi
    done
}

case "$1" in
    start)
    getPid
    if [ "$pid" ]; then
        echo -e "\033[1;33m[W]\033[0m  $name already running. pid = $pid"
        exit 2
    else
        doStart
    fi
    ;;

    stop)
    getPid
    if [ "$pid" ]; then
        doStop
    else
        echo -e "\033[1;33m[W]\033[0m  $name not running."
        exit 2
    fi
    ;;

    kill)
    getPid
    if [ "$pid" ]; then
        echo -e "\033[1;36m[I]\033[0m  Fast shutdown $name..."
        kill -TERM $pid
        echo -e "\033[1;32m[N]\033[0m  Shutdown $name Done."
    else
        echo -e "\033[1;33m[W]\033[0m  $name not running."
        exit 2
    fi
    ;;

    reload)
    getPid
    if [ "$pid" ]; then
        echo -e "\033[1;36m[I]\033[0m  Reloading $name configuration file..."
        kill -USR2 $pid
        echo 'Done.'
    else
        echo -e "\033[1;33m[W]\033[0m  $name not running"
        doStart
    fi
    ;;

    restart)
    getPid
    if [ "$pid" ]; then
        echo -e "\033[1;36m[I]\033[0m  Restarting $name: "
        doStop
        doStart
    else
        echo -e "\033[1;33m[W]\033[0m  $name not running"
        doStart
    fi
    ;;

    status)
    getPid
    if [ "$pid" ]; then
        echo -e "\033[1;32m[N]\033[0m  $name is running. pid = $pid"
    else
        echo -e "\033[1;32m[N]\033[0m  $name not running."
    fi
    ;;

    *)
    echo "Usage: $0 {start|stop|kill|reload|restart|status}." >&2
    exit 3
    ;;
esac

exit 0
